---
# tasks file for python

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: python

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: python

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: python

- name: Create pyenv download directory
  file: >
    path={{ pyenv_install_dir }}
    owner=root
    group=root
    mode=0755
    state=directory
  tags: python

- name: Download pyenv
  git: >
    repo={{ pyenv_repo }}
    dest={{ pyenv_install_dir }}
    version=v{{ pyenv_version }}
  tags: python

- name: Create pyenv shims directory
  file: >
    path={{ pyenv_install_dir }}/shims
    owner=root
    group=root
    mode=0755
    state=directory
  tags: python

- name: Create pyenv versions directory
  file: >
    path={{ pyenv_install_dir }}/versions
    owner=root
    group=root
    mode=0755
    state=directory
  tags: python

- name: Add pyenv to global shell profile
  template: >
    src=pyenv.sh.j2
    dest=/etc/profile.d/pyenv.sh
    owner=root
    group=root
    mode=0644
  tags: python

- name: Install Python 3
  shell: pyenv install {{ python3_version }}
  environment:
    PATH: "{{ pyenv_install_dir }}/bin:{{ ansible_env.PATH }}"
    PYENV_ROOT: "{{ pyenv_install_dir }}"
  args:
    creates: "{{ pyenv_install_dir }}/versions/{{ python3_version }}/bin/python"
  when: python3_enabled
  tags: python

- name: Install Python 2
  shell: pyenv install {{ python2_version }}
  environment:
    PATH: "{{ pyenv_install_dir }}/bin:{{ ansible_env.PATH }}"
    PYENV_ROOT: "{{ pyenv_install_dir }}"
  args:
    creates: "{{ pyenv_install_dir }}/versions/{{ python2_version }}/bin/python"
  when: python2_enabled
  tags: python

- name: Set default Python
  template: >
    src=version.j2
    dest="{{ pyenv_install_dir }}/version"
    owner=root
    group=root
    mode=0644
  tags: python
